# Generated by Django 4.0.5 on 2022-06-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0001_initial'),
        ('animals', '0002_animal_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='characteristics',
            field=models.ManyToManyField(related_name='animals', to='characteristics.characteristic'),
        ),
    ]
